[tool.pyright]
exclude = [
    "**/__pycache__",
    "data",
]
reportGeneralTypeIssues = "none"
reportOptionalMemberAccess = "none"
reportUnnecessaryTypeIgnoreComment = "warning"
reportUnusedImport = "warning"
pythonVersion = "3.9"
typeCheckingMode = "basic"